const FilterJson = {
  location: [
    "Canada",
    "USA",
    "India",
    "UK",
    "Mexico",
    "Russia",
    "Turkey",
    "Japan",
    "China",
    "Nepal",
    "Other",
  ],
  category: [
    "House Hold",
    "Typing",
    "Computer Operator",
    "Teacher",
    "Hr",
    "CEO",
    "Recepection",
    "Frontend developer",
    "Backend developer",
    "Devops developer",
    "Intership",
    "House",
    "Doctor",
    "Domestic",
    "Nurse",
    "Other",
    "IT",
  ],
  education: [
    "Bsc",
    "Msc",
    "B. Tech",
    "M. Tech",
    "BCA",
    "BBA",
    "MCA",
    "Bcom",
    "Mcom",
    "BBA",
    "Other",
  ],
  qualification: [
    "Metric",
    "Post Metric",
    "Diploma",
    "Graduate",
    "Post Graduate",
    "Phd",
    "Other",
  ],
  salary: [
    "Below 1 Lac",
    "1Lac-3Lac",
    "3Lac-5Lac",
    "5Lac-10Lac",
    "Above 10Lac",
    "Not Disclosed",
    "Other",
  ],
  industry: ["Hospitality", "Transport", "IT", "Tourism", "Health", "Other"],
  experience: ["Fresher", "0-1 ", "1-3 ", "3-5 ", "5-7 ", "7+ ", "Other"],
  job_type: [
    "Full Time",
    "Part Time",
    "Full Time with SWAP",
    "Part Time with SWAP",
    "SWAP Only",
    "Other than SWAP",
    "Other",
  ],
  swap: ["Yes", "No"],
  employement: ["Full Time", "Part Time", "Other"],

  corporation: ["B2B", "B2C", "C2C", "B2G", "G2C", "Other"],
  keyskill: ["JAVA", "HTML", "CSS", "REACT", "PHP", "Python", "Other"],
  course: [
    "MA",
    "BA",
    "B.com",
    "M.com",
    "CA",
    "MBBS",
    "BDS",
    "PHD",
    "M.tech",
    "B.tech",
    "BBA",
    "MBA",
    "CPCT",
    "Other",
  ],
  Specialization: ["Maths", "Bio", "Phy", "Social Studies", "Core", "Other"],
  Language: ["English", "Hindi", "French", "Gujrati", "Marathi", "Other"],
  AdminType: ["Manager", "Sub-admin", "Admin", "Super-Admin"],
  lmia_status: ["Pending", "Approved", "Reject", "Draft", "Complete", "Other"],
  Duration: ["Last week", "Last month", "last 3 months", "Last year"],
};
export default FilterJson;
