const FilterJson = {
  location: [
    "Canada",
    "USA",
    "India",
    "UK",
    "Mexico",
    "Russia",
    "Turkey",
    "Japan",
    "China",
    "Nepal",
    "Other",
  ],
  category: [
    "Typing",
    "Computer Operator",
    "Teacher",
    "Hr",
    "CEO",
    "Recepection",
    "Frontend developer",
    "Backend developer",
    "Devops developer",
    "Intership",
    "House",
    "Doctor",
    "Domestic",
    "Nurse",
    "Other",
  ],
  education: [
    "Metric",
    "Post Metric",
    "Diploma",
    "Graduate",
    "Post Graduate",
    "Other",
  ],
  salary: [
    "Below 1 Lac",
    "1Lac-3Lac",
    "3Lac-5Lac",
    "5Lac-8Lac",
    "9Lac-10Lac",
    "Above 10Lac",
    "Not Disclosed",
    "Other",
  ],
  industry: ["Hospitality", "Transport", "IT", "Tourism", "Health", "Other"],
  experience: ["Fresher", "0-1 ", "1-3 ", "3-5 ", "5+ ", "10+ ", "Other"],
  job_type: [
    "Full Time",
    "Part Time",
    "Full Time with SWAP",
    "Part Time with SWAP",
    "SWAP Only",
    "Other than SWAP",
    "Other",
  ],
  swap: ["Yes", "No"],
  employement: ["Full Time", "Part Time", "Other"],
  qualification: [
    "Graduate",
    "Post graduate",
    "PHD",
    "12th Pass",
    "Bds",
    "Doctor",
    "Other",
  ],
  corporation: ["B2B", "B2C", "C2C", "B2G", "G2C", "Other"],
  keyskill: ["java", "html", "css", "React", "php", "python", "Other"],
  course: [
    "MA",
    "BA",
    "B.com",
    "M.com",
    "CA",
    "MBBS",
    "BDS",
    "PHD",
    "M.tech",
    "B.tech",
    "BBA",
    "MBA",
    "CPCT",
    "Other",
  ],
  Specialization: ["Maths", "Bio", "phy", "Social studies", "core", "Other"],
  Language: ["English", "Hindi", "French", "Gujrati", "Marathi", "Other"],
  AdminType: ["manager", "sub-admin", "admin", "super-admin"],
  lmia_status: ["pending", "approved", "reject", "draft", "complete", "Other"],
};
export default FilterJson;
