const filterjson = {
  location: [
    "afghanistan",
    "aland islands",
    "albania",
    "algeria",
    "american samoa",
    "andorra",
    "angola",
    "anguilla",
    "antarctica",
    "antigua and barbuda",
    "argentina",
    "armenia",
    "aruba",
    "australia",
    "austria",
    "azerbaijan",
    "bahamas",
    "bahrain",
    "bangladesh",
    "barbados",
    "belarus",
    "belgium",
    "belize",
    "benin",
    "bermuda",
    "bhutan",
    "bolivia",
    "bosnia and herzegovina",
    "botswana",
    "bouvet island",
    "brazil",
    "british indian ocean territory",
    "brunei darussalam",
    "bulgaria",
    "burkina faso",
    "burundi",
    "cambodia",
    "cameroon",
    "canada",
    "cape verde",
    "cayman islands",
    "central african rrepublic",
    "chad",
    "chile",
    "china",
    "christmas island",
    "cocos (keeling) islands",
    "colombia",
    "comoros",
    "congo",
    "congo, the democratic republic of the",
    "cook islands",
    "costa rica",
    "cote d'ivoire",
    "croatia",
    "cuba",
    "cyprus",
    "czech republic",
    "denmark",
    "djibouti",
    "dominica",
    "dominican republic",
    "ecuador",
    "egypt",
    "el salvador",
    "equatorial guinea",
    "eritrea",
    "estonia",
    "ethiopia",
    "falkland islands (malvinas)",
    "faroe islands",
    "fiji",
    "finland",
    "france",
    "french guiana",
    "french polynesia",
    "french southern territories",
    "gabon",
    "gambia",
    "georgia",
    "germany",
    "ghana",
    "gibraltar",
    "greece",
    "greenland",
    "grenada",
    "guadeloupe",
    "guam",
    "guatemala",
    "guernsey",
    "guinea",
    "guinea-bissau",
    "guyana",
    "haiti",
    "heard island and mcdonald islands",
    "holy see (vatican city state)",
    "honduras",
    "hong kong",
    "hungary",
    "iceland",
    "india",
    "indonesia",
    "iran, islamic republic of",
    "iraq",
    "ireland",
    "isle of man",
    "israel",
    "italy",
    "jamaica",
    "japan",
    "jersey",
    "jordan",
    "kazakhstan",
    "kenya",
    "kiribati",
    "korea, democratic people's republic of",
    "korea, republic of",
    "kuwait",
    "kyrgyzstan",
    "lao people's democratic republic",
    "latvia",
    "lebanon",
    "lesotho",
    "liberia",
    "libyan arab jamahiriya",
    "liechtenstein",
    "lithuania",
    "luxembourg",
    "macao",
    "macedonia, the former yugoslav republic of",
    "madagascar",
    "malawi",
    "malaysia",
    "maldives",
    "mali",
    "malta",
    "marshall islands",
    "martinique",
    "mauritania",
    "mauritius",
    "mayotte",
    "mexico",
    "micronesia, federated states of",
    "moldova, republic of",
    "monaco",
    "mongolia",
    "montserrat",
    "morocco",
    "mozambique",
    "myanmar",
    "namibia",
    "nauru",
    "nepal",
    "netherlands",
    "netherlands antilles",
    "new caledonia",
    "new zealand",
    "nicaragua",
    "niger",
    "nigeria",
    "niue",
    "norfolk island",
    "northern mariana islands",
    "norway",
    "oman",
    "pakistan",
    "palau",
    "palestinian territory, occupied",
    "panama",
    "papua new guinea",
    "paraguay",
    "peru",
    "philippines",
    "pitcairn",
    "poland",
    "portugal",
    "puerto rico",
    "qatar",
    "reunion",
    "romania",
    "russian federation",
    "rwanda",
    "saint helena",
    "saint kitts and nevis",
    "saint lucia",
    "saint pierre and miquelon",
    "saint vincent and the grenadines",
    "samoa",
    "san marino",
    "sao tome and principe",
    "saudi arabia",
    "senegal",
    "serbia and montenegro",
    "seychelles",
    "sierra leone",
    "singapore",
    "slovakia",
    "slovenia",
    "solomon islands",
    "somalia",
    "south africa",
    "south georgia and the south sandwich islands",
    "spain",
    "sri lanka",
    "sudan",
    "suriname",
    "svalbard and jan mayen",
    "swaziland",
    "sweden",
    "switzerland",
    "syrian arab republic",
    "taiwan, province of china",
    "tajikistan",
    "tanzania, united republic of",
    "thailand",
    "timor-leste",
    "togo",
    "tokelau",
    "tonga",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "turks and caicos islands",
    "tuvalu",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "united states minor outlying islands",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "venezuela",
    "viet nam",
    "virgin islands, british",
    "virgin islands, u.s.",
    "wallis and futuna",
    "western sahara",
    "yemen",
    "zambia",
    "zimbabwe",
  ],
  category: [
    "house hold",
    "typing",
    "computer operator",
    "teacher",
    "hr",
    "ceo",
    "recepection",
    "frontend developer",
    "backend developer",
    "devops developer",
    "intership",
    "house",
    "doctor",
    "domestic",
    "nurse",
    "other",
    "it",
    "medical",
  ],
  education: [
    "bsc",
    "msc",
    "b. tech",
    "m. tech",
    "bca",
    "bba",
    "mca",
    "bcom",
    "mcom",
    "other",
  ],
  qualification: [
    "metric",
    "post metric",
    "diploma",
    "graduate",
    "post graduate",
    "phd",
    "other",
  ],
  salary: [
    "below 1 lac",
    "1lac-3lac",
    "3lac-5lac",
    "5lac-10lac",
    "above 10lac",
    "not disclosed",
    "other",
  ],
  industry: [
    "retail & wholesale",
    "healthcare",
    "manufacturing",
    "construction, repair & maintenance services",
    "restaurants & food service",
    "finance",
    "human resources & staffing",
    "transportation & logistics",
    "information technology",
    "energy, mining, utilities",
    "management & consulting",
    "non-profit & ngo",
    "education",
    "insurance",
    "government & public administration",
    "telecommunications",
    "aerospace & defence",
    "hotel & travel accommodation",
    "agriculture",
    "legal",
    "real estate",
    "media & communication",
    "arts, entertainment & recreation",
    "pharmaceutical & biotechnology",
    "personal consumer services",
  ],
  experience: [
    "fresher",
    "0-1 ",
    "1-2 ",
    "2-3 ",
    "3-5 ",
    "5-7 ",
    "7+ ",
    "other",
  ],
  job_type: [
    "full-time",
    "permanent",
    "part-time",
    "contract",
    "temporary",
    "casual",
    "apprenticeship",
    "internship",
    "freelance",
    "swep",
    "other",
  ],
  swap: ["yes", "no"],
  employement: ["full-time", "part-time", "other"],
  corporation: ["b2b", "b2c", "c2c", "b2g", "g2c", "other"],
  keyskill: [
    "sales, retail, & customer cupport occupations",
    "healthcare occupations",
    "organization operations & administrative occupations",
    "food & oeverage occupations",
    "technology occupations",
    "finance & accounting occupations",
    "repair, maintenance & installation occupations",
    "architecture & engineering occupations",
    "construction & extraction occupations",
    "supply chain & logistics occupations",
    "manufacturing & utilities occupations",
    "marketing, advertising & public relations occupations",
    "community & social services occupations",
    "education & instruction occupations",
    "transportation occupations",
    "science & research occupations",
    "cleaning & grounds maintenance occupations",
    "media, arts & design occupations",
    "safety, security & civil defence occupations",
    "personal service occupations",
    "travel, attractions & events occupations",
    "legal occupations",
    "farming, fisheries & forestry occupations ",
  ],
  course: [
    "ma",
    "ma",
    "b.com",
    "m.com",
    "ca",
    "mbbs",
    "bds",
    "phd",
    "m.tech",
    "b.tech",
    "bba",
    "mba",
    "cpct",
    "other",
  ],
  specialization: ["maths", "bio", "phy", "social studies", "core", "other"],
  language: [
    "abkhaz",
    "afar",
    "afrikaans",
    "akan",
    "albanian",
    "amharic",
    "arabic",
    "aragonese",
    "armenian",
    "assamese",
    "avaric",
    "avestan",
    "aymara",
    "azerbaijani",
    "bambara",
    "bashkir",
    "basque",
    "belarusian",
    "bengali",
    "bihari",
    "bislama",
    "bosnian",
    "breton",
    "bulgarian",
    "burmese",
    "catalan- valencian",
    "chamorro",
    "chechen",
    "chichewa- chewa- nyanja",
    "chinese",
    "chuvash",
    "cornish",
    "corsican",
    "cree",
    "croatian",
    "czech",
    "danish",
    "divehi- dhivehi- maldivian-",
    "dutch",
    "english",
    "esperanto",
    "estonian",
    "ewe",
    "faroese",
    "fijian",
    "finnish",
    "french",
    "fula- fulah- pulaar- pular",
    "galician",
    "georgian",
    "german",
    "greek, modern",
    "guaraní",
    "gujarati",
    "haitian- haitian creole",
    "hausa",
    "hebrew (modern)",
    "herero",
    "hindi",
    "hiri motu",
    "hungarian",
    "interlingua",
    "indonesian",
    "interlingue",
    "irish",
    "igbo",
    "inupiaq",
    "ido",
    "icelandic",
    "italian",
    "inuktitut",
    "japanese",
    "javanese",
    "kalaallisut, greenlandic",
    "kannada",
    "kanuri",
    "kashmiri",
    "kazakh",
    "khmer",
    "kikuyu, gikuyu",
    "kinyarwanda",
    "kirghiz, kyrgyz",
    "komi",
    "kongo",
    "korean",
    "kurdish",
    "kwanyama, kuanyama",
    "latin",
    "luxembourgish, letzeburgesch",
    "luganda",
    "limburgish",
    "lingala",
    "lao",
    "lithuanian",
    "luba-katanga",
    "latvian",
    "manx",
    "macedonian",
    "malagasy",
    "malay",
    "malayalam",
    "maltese",
    "māori",
    "marathi (marāṭhī)",
    "marshallese",
    "mongolian",
    "mauru",
    "navajo, navaho",
    "norwegian bokmål",
    "north ndebele",
    "nepali",
    "ndonga",
    "norwegian nynorsk",
    "norwegian",
    "suosu",
    "south ndebele",
    "occitan",
    "ojibwe",
    "old church slavonic",
    "oromo",
    "oriya",
    "ossetian, ossetic",
    "panjabi, punjabi",
    "pāli",
    "persian",
    "polish",
    "pashto",
    "portuguese",
    "quechua",
    "romansh",
    "kirundi",
    "romanian",
    "russian",
    "sanskrit",
    "sardinian",
    "sindhi",
    "northern sami",
    "samoan",
    "sango",
    "serbian",
    "scottish gaelic-",
    "shona",
    "sinhala, sinhalese",
    "slovak",
    "slovene",
    "somali",
    "southern sotho",
    "spanish- castilian",
    "sundanese",
    "swahili",
    "swati",
    "swedish",
    "tamil",
    "telugu",
    "tajik",
    "thai",
    "tigrinya",
    "tibetan standard, tibetan, central",
    "turkmen",
    "tagalog",
    "tswana",
    "tonga (tonga islands)",
    "turkish",
    "tsonga",
    "tatar",
    "twi",
    "tahitian",
    "uighur, uyghur",
    "ukrainian",
    "urdu",
    "uzbek",
    "venda",
    "vietnamese",
    "volapük",
    "walloon",
    "welsh",
    "wolof",
    "western frisian",
    "xhosa",
    "yiddish",
    "yoruba",
    "zhuang, chuang",
  ],
  admintype: ["super-admin", "admin", "manager", "executive"],
  duration: ["last week", "last month", "last 3 months", "last year"],
  employee_status: [
    "new",
    "prospect",
    "lead",
    "retained",
    "lost",
    "dead",
    "working on",
    "submitted",
  ],
  interested: [
    "swep",
    "internship",
    "co-op",
    "part-time",
    "full-time",
    "contract",
    "all",
  ],
  lmia_status: [
    // "need to start",
    // "job bank requested",
    // "working on it",
    // "additional information required",
    // "application in review",
    // "advertisement running",
    // "application submitted",
    // "payment done",
    // "interview done",
    // "lmia approved",
    // "limia rejected",
    // "lmia partial",
    // "position approved",
    "onboarding",
    "advertisements",
    "documentation",
    "candidate placement",
    "submission",
    "decision",
  ],
  lima_sub_stages: {
    onboarding: [
      "request email id",
      "contact number",
      "introduction email",
      "job bank creation",
      "intake sheet completion",
    ],
    advertisements: [
      "job bank account",
      "advertise on job bank and 3 portals.",
    ],
    documentation: [
      "Once ads are matured",
      "Follow up",
      // "birth certificate",
      // "marriage certificate",
      // "education docs",
      // "p c c (all countries)",
      // "upfront Medica",
      // "employment ref letter",
      // "current employment",
      // "digital photo",
      // "passport",
      // "resume/cv",
      // "bank statement",
      // "payslips",
      // "i t r",
      // "i e l t s",
      // "any past refusal",
      // "proof of current immifration status",
      // "biometrics(is given)",
      // "lmia, job offer, job contact will be arrange by us"
    ],
    "candidate placement": [
      "confirm status of candidates",
      "attain information on candidate",
      "employer's work permit plans",
    ],
    submission: [
      "initiate  l m i a application on portal",
      "fill job details and docs from employer",
      "attach relevant documents",
      "request harpreet Ma'am's review",
      "attest and submit on portal",
      "await payment request",
      "inform employer of payment and potential interview",
    ],
    decision: [
      "awaiting decision",
      "approved",
      "rejected",
      // "maintain mature ads throughout the process",
      // "initiate app after ads mature",
      // "email employer for updates",
      // "request extra docs if needed",
      // "keep them updated on app status",
    ],
  },
  visa_status: [
    "onboard",
    "documentation",
    "file preparation",
    "file review",
    "file submission",
    "file decision",
  ],
  visa_sub_stages: {
    onboard: ["sending a document checklist", "ra invoice processing"],
    documentation: [
      "birthth certificate",
      "marriage certificate",
      "education docs",
      "p c c (all countries)",
      "upfront Medica",
      "employment ref letter",
      "current employment",
      "digital photo",
      "passport",
      "resume/cv",
      "bank statement",
      "payslips",
      "i t r",
      "i e l t s",
      "any past refusal",
      "proof of current immifration status",
      "biometrics(is given)",
      "lmia, job offer, job contact will be arrange by us",
    ],
    "file preparation": [
      "reviewing documents",
      "i m m 1295",
      "i m m 5476",
      "i m m 5645",
      "representative submission letter",
    ],
    "file review": ["create account on authorized representative portal"],
    "file decision": ["awaiting decision", "approved", "rejected"],
  },
  canadian_candidate_status: [
    "Visitor",
    "Student",
    "Post Grad Work Permit",
    "Open WorkPermit",
    "LMIA Closed Work permit",
    "Spousal Open Work Permit",
  ],
};
export default filterjson;
